### ISSUE TITLE
Can you provide the source code， thanks！！

### ISSUE THREAD

**Issue by guojingsai** [allenchen8210/ros_multi_gmsl_px2#1]

**Comment by allenchen8210** [comment]
hi, guojingsai
this is just tutorial, u can follow process to install it.

**Comment by guojingsai** [comment]
Thanks for your reply, I have tried to install, but I can't find driveworks, how can I modify the makelist configuration file, can you give some suggestions, and can I directly compile on px2,  thanks  again.

**Comment by allenchen8210** [comment]
hi, guojingsai 
I modify FindDriveworks.cmake, dirctily give abosolute path. And u can compile this ros node on PX2. 

```
set(Driveworks_INCLUDE_DIR /usr/local/driveworks/include/)
set(Driveworks_LIBRARY /usr/local/driveworks/lib/)
set(Driveworks_PROCESS_INCLUDES Driveworks_INCLUDE_DIR)
set(Driveworks_PROCESS_LIBS Driveworks_LIBRARY)
libfind_process(Driveworks)
```

**Comment by guojingsai** [comment]
hi, allenchen8210
Thank you for your help, I have successfully solved this problem.
